name: cancer-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.24.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - scikit-learn>=1.2.0
  - jupyter>=1.0.0
  - xgboost>=1.7.0
  - pip
  - pip:
    - tensorflow>=2.12.0
    - kagglehub>=0.2.0
    - imbalanced-learn>=0.11.0
    - optuna>=3.0.0
